---
- name: Retrieve Checkpoint File
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Retrieve Checkpoint
      napalm_get_facts:
        filter: checkpoint_file
        optional_args:
          port: 8443

    #- debug: 
    #    msg: "{{ napalm_checkpoint_file.splitlines() }}"
    - name: Save Checkpoint File
      copy:
        content: "{{ napalm_checkpoint_file }}"
        dest: "{{ inventory_hostname }}.txt"