---
- name: NAPALM get_facts and get interfaces
  hosts: nxos
  gather_facts: False
  tasks: 
    - name: napalm get_facts
      napalm_get_facts:
        filter: facts,interfaces
        optional_args:
         port: 8443
    
    - debug:
        msg: "{{ hostvars[inventory_hostname] }}" 

    - debug:
        var: napalm_port