---
- name: NAPALM get_facts and get interfaces
  hosts: juniper
  gather_facts: False
  tasks: 
    - name: napalm get_facts
      napalm_get_facts:
        filter: facts
    
    - debug:
        var: napalm_facts

    - debug:
        var: ansible_connection