---
- name: NAPALM get_arp_table and get_mac_address_table
  hosts: cisco:arista
  gather_facts: False
  tasks:
    - name: napalm getters
      napalm_get_facts:
        filter: arp_table,mac_address_table
    - name: Print arp table
      debug:
        var: napalm_arp_table
    - name: Print mac_address_table
      debug:
        var: napalm_mac_address_table
    