---
- name: NAPALM Config merge
  hosts: arista2
  gather_facts: False
  tasks:
    - name: Napalm Configuration
      napalm_install_config:
        replace_config: False
        commit_changes: True
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
        config: |
          interface Loopback98
            ip address 10.1.98.2/24
          interface Loopback99
            ip address 10.1.99.2/24